import { nativeInputHint } from "./parse.ts";
import type { NormalizedQuestion, NormalizedRequest } from "./types.ts";

/**
 * The no-UI route.
 *
 * This formatter is the single source of truth for the plain-text questionnaire.
 * It is never generated by the model. The output adapter appends it to the
 * assistant output *after the model's final answer is complete* and before
 * control returns to the caller; the caller's next turn replies with an ordinary
 * user message and the model interprets it without any option ids or a second UI
 * call.
 *
 * A generic host that cannot hook the final assistant output has no way to
 * guarantee that ordering; in that case the adapter reports `no_output_hook` and
 * the caller must deliver this text itself rather than claim it was appended.
 *
 * Format, per question:
 *   - a numbered title line
 *   - the optional prompt line
 *   - an input-hint line (single / multi / free input)
 *   - one line per option
 *   - a free-input line, always last
 */

const INTRO = "AskUserUI：需要你的选择。当前环境没有可交互界面，请直接在下一条消息里回复你的选择。";

function questionBlock(question: NormalizedQuestion, total: number): string[] {
	const lines: string[] = [];
	lines.push(`问题 ${question.index + 1}/${total}：${question.title}`);
	if (question.prompt && question.prompt.trim() !== "") {
		lines.push(`  说明：${question.prompt.trim()}`);
	}
	lines.push(`  输入提示：${nativeInputHint(question)}`);
	question.options.forEach((option, optionIndex) => {
		const description = option.description?.trim();
		const suffix = description ? ` — ${description}` : "";
		lines.push(`    [${optionIndex + 1}] ${option.label}${suffix}`);
	});
	if (question.hasDefault && question.default !== undefined) {
		lines.push(`    默认值：${question.default}（可不回复，直接使用默认值）`);
	}
	if (question.kind === "input") {
		lines.push("    自由输入：直接回复你的文本作为答案");
	} else {
		lines.push("    自由输入：直接回复你的文本作为答案（可与编号组合，写作 “编号 | 说明”）");
	}
	return lines;
}

export function formatPlainText(request: NormalizedRequest): string {
	const lines: string[] = [INTRO];
	if (request.header && request.header.trim() !== "") {
		lines.push(request.header.trim());
	}
	request.questions.forEach((question) => {
		lines.push("");
		lines.push(...questionBlock(question, request.questions.length));
	});
	return lines.join("\n");
}
